# Generated by Django 6.0.6 on 2026-07-06 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bezugsperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fragebogen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JugendlichePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Frage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('kategorie', models.CharField(max_length=100)),
                ('reihenfolge', models.IntegerField()),
                ('fragebogen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragen', to='fragebogen.fragebogen')),
            ],
        ),
        migrations.CreateModel(
            name='FragebogenAntworten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bewertet_von', models.CharField(choices=[('JugendlichePerson', 'Jugendliche Person'), ('Bezugsperson', 'Bezugsperson')], max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('Bezugsperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fragebogen.bezugsperson')),
                ('JugendlichePerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='fragebogen.jugendlicheperson')),
            ],
        ),
        migrations.CreateModel(
            name='PartResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antwort_wert', models.IntegerField()),
                ('kommentar', models.TextField(blank=True, null=True)),
                ('FragebogenAntworten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='fragebogen.fragebogenantworten')),
                ('frage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fragebogen.frage')),
            ],
        ),
    ]
