# Generated by Django 6.0.6 on 2026-07-08 09:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbschnittAntwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kommentar', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AbschnittFrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reihenfolge', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bezugsperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('kuerzel', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fragebogen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FrageVorlage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='JugendlichePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FrageAntwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antwort_wert', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('motivations_wert', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('abschnitt_antwort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antworten', to='fragebogen.abschnittantwort')),
                ('frage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fragebogen.abschnittfrage')),
            ],
        ),
        migrations.CreateModel(
            name='FragebogenAbschnitt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('reihenfolge', models.PositiveIntegerField()),
                ('fragebogen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abschnitte', to='fragebogen.fragebogen')),
            ],
        ),
        migrations.AddField(
            model_name='abschnittfrage',
            name='fragebogen_abschnitt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragen', to='fragebogen.fragebogenabschnitt'),
        ),
        migrations.AddField(
            model_name='abschnittantwort',
            name='fragebogen_abschnitt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fragebogen.fragebogenabschnitt'),
        ),
        migrations.CreateModel(
            name='FragebogenAntwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bewertet_von', models.CharField(choices=[('JugendlichePerson', 'Jugendliche Person'), ('Bezugsperson', 'Bezugsperson')], max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('bezugsperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fragebogen.bezugsperson')),
                ('fragebogen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fragebogen.fragebogen')),
                ('jugendliche_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragebogen_antworten', to='fragebogen.jugendlicheperson')),
            ],
        ),
        migrations.AddField(
            model_name='abschnittantwort',
            name='fragebogen_antwort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abschnitt_antworten', to='fragebogen.fragebogenantwort'),
        ),
        migrations.AddField(
            model_name='abschnittfrage',
            name='frage_vorlage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verwendungen', to='fragebogen.fragevorlage'),
        ),
    ]
