# Generated by Django 6.0.6 on 2026-07-10 07:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbschnittAntwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kommentar', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AbschnittFrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reihenfolge', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fragebogen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FrageVorlage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='JugendlichePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bezugsperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('kuerzel', models.CharField(blank=True, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bezugsperson', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Einladung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('benutzt', models.BooleanField(default=False)),
                ('bezugsperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fragebogen.bezugsperson')),
            ],
        ),
        migrations.CreateModel(
            name='FrageAntwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antwort_wert', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('abschnitt_antwort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antworten', to='fragebogen.abschnittantwort')),
                ('frage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fragebogen.abschnittfrage')),
            ],
        ),
        migrations.CreateModel(
            name='FragebogenAbschnitt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('reihenfolge', models.PositiveIntegerField()),
                ('fragebogen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abschnitte', to='fragebogen.fragebogen')),
            ],
        ),
        migrations.AddField(
            model_name='abschnittfrage',
            name='fragebogen_abschnitt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragen', to='fragebogen.fragebogenabschnitt'),
        ),
        migrations.AddField(
            model_name='abschnittantwort',
            name='fragebogen_abschnitt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fragebogen.fragebogenabschnitt'),
        ),
        migrations.CreateModel(
            name='FragebogenAntwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('einladung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antwort', to='fragebogen.einladung')),
            ],
        ),
        migrations.AddField(
            model_name='abschnittantwort',
            name='fragebogen_antwort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abschnitt_antworten', to='fragebogen.fragebogenantwort'),
        ),
        migrations.CreateModel(
            name='FragebogenFall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('fragebogen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fragebogen.fragebogen')),
                ('jugendliche_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faelle', to='fragebogen.jugendlicheperson')),
            ],
        ),
        migrations.AddField(
            model_name='einladung',
            name='fall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einladungen', to='fragebogen.fragebogenfall'),
        ),
        migrations.AddField(
            model_name='abschnittfrage',
            name='frage_vorlage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fragebogen.fragevorlage'),
        ),
        migrations.AddConstraint(
            model_name='fragebogenabschnitt',
            constraint=models.UniqueConstraint(fields=('fragebogen', 'reihenfolge'), name='unique_section_order'),
        ),
        migrations.AddConstraint(
            model_name='fragebogenfall',
            constraint=models.UniqueConstraint(fields=('jugendliche_person', 'fragebogen'), name='unique_questionnaire_case'),
        ),
    ]
