# Generated by Django 6.0.6 on 2026-07-09 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fragebogen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frageantwort',
            name='motivations_wert',
        ),
    ]
