# Generated by Django 6.0.6 on 2026-07-07 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragebogen', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartResponse',
            new_name='FrageAntwort',
        ),
        migrations.RenameModel(
            old_name='Abschnitt',
            new_name='FragebogenAbschnitt',
        ),
        migrations.RenameModel(
            old_name='FrageTemplate',
            new_name='FrageVorlage',
        ),
        migrations.RenameField(
            model_name='abschnittantwort',
            old_name='abschnitt',
            new_name='fragebogen_abschnitt',
        ),
        migrations.RenameField(
            model_name='abschnittfrage',
            old_name='frage_template',
            new_name='frage_vorlage',
        ),
        migrations.RenameField(
            model_name='abschnittfrage',
            old_name='abschnitt',
            new_name='fragebogen_abschnitt',
        ),
        migrations.CreateModel(
            name='FragebogenAntwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bewertet_von', models.CharField(choices=[('JugendlichePerson', 'Jugendliche Person'), ('Bezugsperson', 'Bezugsperson')], max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('bezugsperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fragebogen.bezugsperson')),
                ('fragebogen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fragebogen.fragebogen')),
                ('jugendliche_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragebogen_antworten', to='fragebogen.jugendlicheperson')),
            ],
        ),
        migrations.AlterField(
            model_name='abschnittantwort',
            name='fragebogen_antwort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abschnitt_antworten', to='fragebogen.fragebogenantwort'),
        ),
        migrations.DeleteModel(
            name='FragebogenAntworten',
        ),
    ]
