# Generated by Django 6.0.6 on 2026-07-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragebogen', '0002_remove_frageantwort_motivations_wert'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='abschnittfrage',
            constraint=models.UniqueConstraint(fields=('fragebogen_abschnitt', 'reihenfolge'), name='unique_question_order'),
        ),
        migrations.AddConstraint(
            model_name='fragebogenabschnitt',
            constraint=models.UniqueConstraint(fields=('fragebogen', 'reihenfolge'), name='unique_section_order'),
        ),
    ]
