# Generated by Django 6.0.6 on 2026-07-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fragebogen', '0002_alter_bezugsperson_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fragebogenfall',
            options={'ordering': ['-erstellt_am']},
        ),
        migrations.RemoveConstraint(
            model_name='fragebogenfall',
            name='unique_questionnaire_case',
        ),
    ]
