# Generated by Django 6.0.6 on 2026-07-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragebogen', '0003_abschnittfrage_unique_question_order_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='abschnittantwort',
            constraint=models.UniqueConstraint(fields=('fragebogen_antwort', 'fragebogen_abschnitt'), name='unique_section_answer'),
        ),
        migrations.AddConstraint(
            model_name='frageantwort',
            constraint=models.UniqueConstraint(fields=('abschnitt_antwort', 'frage'), name='unique_question_answer'),
        ),
    ]
