# Generated by Django 6.0.6 on 2026-08-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fragebogen', '0003_alter_fragebogenfall_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abschnittantwort',
            options={'verbose_name': 'Abschnitts-Antwort', 'verbose_name_plural': 'Abschnitts-Antworten'},
        ),
        migrations.AlterModelOptions(
            name='abschnittfrage',
            options={'verbose_name': 'Abschnitts-Frage', 'verbose_name_plural': 'Abschnitts-Fragen'},
        ),
        migrations.AlterModelOptions(
            name='bezugsperson',
            options={'verbose_name': 'Bezugsperson', 'verbose_name_plural': 'Bezugspersonen'},
        ),
        migrations.AlterModelOptions(
            name='einladung',
            options={'verbose_name': 'Einladung', 'verbose_name_plural': 'Einladungen'},
        ),
        migrations.AlterModelOptions(
            name='frageantwort',
            options={'verbose_name': 'Frage-Antwort', 'verbose_name_plural': 'Frage-Antworten'},
        ),
        migrations.AlterModelOptions(
            name='fragebogen',
            options={'verbose_name': 'Fragebogen', 'verbose_name_plural': 'Fragebögen'},
        ),
        migrations.AlterModelOptions(
            name='fragebogenabschnitt',
            options={'verbose_name': 'Fragebogen-Abschnitt', 'verbose_name_plural': 'Fragebogen-Abschnitte'},
        ),
        migrations.AlterModelOptions(
            name='fragebogenantwort',
            options={'verbose_name': 'Fragebogen-Antwort', 'verbose_name_plural': 'Fragebogen-Antworten'},
        ),
        migrations.AlterModelOptions(
            name='fragebogenfall',
            options={'ordering': ['-erstellt_am'], 'verbose_name': 'Fragebogen-Fall', 'verbose_name_plural': 'Fragebogen-Fälle'},
        ),
        migrations.AlterModelOptions(
            name='fragevorlage',
            options={'verbose_name': 'Frage-Vorlage', 'verbose_name_plural': 'Frage-Vorlagen'},
        ),
        migrations.AlterModelOptions(
            name='jugendlicheperson',
            options={'verbose_name': 'Jugendliche Person', 'verbose_name_plural': 'Jugendliche Personen'},
        ),
    ]
